spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

mail:
  address:
    admin: admin@gmail.com
jwt:
  key: pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420