spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-pp013.cyzeevtx5cn7.ap-northeast-2.rds.amazonaws.com:13306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: database
  #h2:
    #console:
      #enabled: true
      #path: /h2
  #datasource:
    #url: jdbc:h2:mem:test

config:
  domain: http://pre013.s3-website.ap-northeast-2.amazonaws.com

mail:
  address:
    admin: admin@gmail.com
jwt:
  key: pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013pre013
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420